swagger: "2.0"
info:
  description: "One Stop Destination for B-school Students"
  version: "3.0.0"
  title: "B-Gyan"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "amit.prag.chanakya@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
tags:
- name: "WeeklyNewsAnalysis"
  description: "Analysis of all important news on weekly basis"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "CurrentAffairAnalysisGDPrepration"
  description: "Analysis of current affair and happening"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /WeeklyNewsAnalysis:
    post:
      tags:
      - "WeeklyNewsAnalysis"
      summary: "Repository of Weekly News Analysis"
      description: ""
      operationId: "uploadWeeklyNewsAnalysis"
      consumes:
      - multipart/form-data
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: upfile
        type: file
        required: true
        description: The file to upload.
      - in: formData
        name: author
        type: string
        required: true
        description: Description of file contents.
      - in: formData
        name: date
        type: string
        required: true
        description: Description of file contents.
      responses:
        201:
          description: "News Uploaded"
          schema:
            $ref: "#/definitions/NewsResponseDto"
        405:
          description: "Invalid News Analysis format"
    put:
      tags:
      - "WeeklyNewsAnalysis"
      summary: "Update Existing News"
      description: ""
      operationId: "updateWeeklyNewsAnalysis"
      consumes:
      - multipart/form-data
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: upfile
        type: file
        required: true
        description: The file to upload.
      - in: formData
        name: author
        type: string
        required: true
        description: Description of file contents.
      - in: formData
        name: date
        type: string
        required: true
        description: Description of file contents.
      responses:
        201:
          description: "Updated"
          schema:
            $ref: "#/definitions/NewsResponseDto"
        405:
          description: "Invalid News Analysis format"
    get:
      tags:
      - "WeeklyNewsAnalysis"
      summary: "Get news analysis List"
      description: ""
      operationId: "getAllNewsIdList"
      responses:
        '200':
          description: "Returned List of All News Id"
          schema:
            $ref: "#/definitions/NewsResponseDtoList"
        '405':
          description: "Invalid input"
  /WeeklyNewsAnalysis/{newsId}:
    delete:
      tags:
      - "WeeklyNewsAnalysis"
      summary: "Delete news analysis"
      description: ""
      operationId: "deleteNewsAnalysis"
      parameters:
      - name: "newsId"
        in: "path"
        description: "Id of news"
        required: true
        type: "string"
      responses:
        200:
          description: "Delete operation with News Id"
          schema:
            $ref: "#/definitions/NewsResponseDto"
        405:
          description: "Invalid input"
  /CAAnalysis:
    post:
      tags:
      - "CurrentAffairAnalysisGDPrepration"
      summary: "Repository of CA Analysis"
      description: ""
      operationId: "uploadCAAnalysis"
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: upfile
        type: file
        required: true
        description: The file to upload.
      - in: formData
        name: author
        type: string
        required: true
        description: Description of file contents.
      - in: formData
        name: date
        type: string
        required: true
        description: Description of file contents.
      - in: formData
        name: section
        type: string
        required: true
        description: Description of section of contents.
      responses:
        201:
          description: "News Uploaded"
          schema:
            $ref: "#/definitions/CAResponseDto"
        405:
          description: "Invalid CA upload Analysis format"
    put:
      tags:
      - "CurrentAffairAnalysisGDPrepration"
      summary: "Update Existing News"
      description: ""
      operationId: "updateCAAnalysis"
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: upfile
        type: file
        required: true
        description: The file to upload.
      - in: formData
        name: author
        type: string
        required: true
        description: Description of file contents.
      - in: formData
        name: date
        type: string
        required: true
        description: Description of file contents.
      - in: formData
        name: section
        type: string
        required: true
        description: Description of section of contents.
      responses:
        201:
          description: "Updated"
          schema:
            $ref: "#/definitions/CAResponseDto"
        405:
          description: "Invalid CA update Analysis format"
  /CAAnalysis/{section}:
    get:
      tags:
      - "CurrentAffairAnalysisGDPrepration"
      summary: "Get CA analysis List"
      description: ""
      operationId: "getAllCAIdList"
      parameters:
      - name: "section"
        in: "path"
        description: "Section of CA"
        required: true
        type: "string"
      responses:
        '200':
          description: "Returned List of All CA Id"
          schema:
            $ref: "#/definitions/CAResponseDtoList"
        '405':
          description: "Invalid input for get all CA Id"
    delete:
      tags:
      - "CurrentAffairAnalysisGDPrepration"
      summary: "Delete all CA analysis of a particular section"
      description: ""
      operationId: "deleteCAAnalysis"
      parameters:
      - name: "section"
        in: "path"
        description: "Section of CA"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully Deleted all CA analysis with specified section"
        405:
          description: "Invalid input to delete CA analysis of section."
  /CAAnalysis/{section}/{CAId}:
    delete:
      tags:
      - "CurrentAffairAnalysisGDPrepration"
      summary: "Delete CA analysis of a particular section with particular ID"
      description: ""
      operationId: "deleteCAAnalysisWithId"
      parameters:
      - name: "section"
        in: "path"
        description: "Section of CA"
        required: true
        type: "string"
      - name: "CAId"
        in: "path"
        description: "Id of CA"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully Deleted CA analysis with specified section and ID"
        405:
          description: "Invalid input to delete CA analysis of section."

definitions:
  NewsResponseDto:
    type: object
    required:
      - id
      - author
    properties:
      id:
        type: string
      author:
        type: string
  NewsResponseDtoList:
    type: object
    required:
      - newsIdList
    properties:
      newsIdList:
        type: array
        items: 
         type: string
  CAResponseDto:
    type: object
    required:
      - id
      - author
      - section
      - date
    properties:
      id:
        type: string
      author:
        type: string
      section:
        type: string
      date:
        type: string
  CAResponseDtoList:
    type: object
    required:
      - CAIdList
    properties:
      CAIdList:
        type: array
        items: 
          $ref: '#/definitions/CAResponseDto'  
  
       
#  ApiResponse:
#    type: "object"
#    properties:
#      code:
#        type: "integer"
#        format: "int32"
#      type:
#        type: "string"
#      message:
#        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
